"use client";
import Link from "next/link";
import { useRouter } from "next/navigation";
import { useEffect, useState } from "react";
import { AdminPanel } from "./AdminPanel";
type User = { id: number; email: string; full_name: string; is_admin: boolean; is_active: boolean; created_at: string; last_login_at: string | null; last_activity_at?: string | null; requests?: number; suspension_reason?: string | null };
type Event = { event_id: string; user_id: number; actor_id: number | null; actor_type: string; action: string; outcome: string; resource_type: string | null; resource_id: string | null; company_rpj: string | null; fiscal_year: number | null; scope: string | null; created_at: string; source: string };
type Audit = { id: number; actor_label: string; action: string; target_user_id: number | null; reason: string; created_at: string; details: unknown };
type Listing = { users: User[]; total: number; page_size: number; tracking_started_at: string };
type History = { events: Event[]; total: number; page_size: number; tracking_started_at: string };
type Summary = { total_users: number; active_users: number; suspended_users: number; registrations: number; users_with_activity: number; analysis_requests: number; report_requests: number; failures: number; recent: Event[]; tracking_started_at: string };
const labels: Record<string,string> = { "account.register":"Registro", "auth.login":"Inicio de sesión", "auth.logout":"Cierre de sesión", "profile.update":"Perfil actualizado", "profile.avatar":"Avatar actualizado", "analysis.request":"Solicitud de análisis", "report.request":"Solicitud de informe", "analysis.state":"Estado del trabajo", "report.state":"Estado del informe", "company.view":"Empresa consultada", "period.change":"Periodo consultado", "source.open":"Fuente abierta", "comparison.view":"Comparación consultada", "search.view":"Buscador abierto", "user.inspect":"Ficha consultada", "user.activity.inspect":"Historial consultado", "user.suspend":"Cuenta suspendida", "user.reactivate":"Cuenta reactivada", "user.revoke_sessions":"Sesiones revocadas", "user.grant_admin":"Permiso administrador concedido", "user.revoke_admin":"Permiso administrador retirado", success:"Correcto", observed:"Observado", created:"Creado", reused:"Reutilizado", retried:"Reintentado", failed:"Fallido", completed:"Completado", queued:"En cola", running:"Procesando", retrying:"Reintentando", review_required:"Requiere revisión" };
const text = (s: string) => labels[s] || s;
const date = (s: string | null | undefined) => s ? new Date(s).toLocaleString("es-PE", { timeZone: "America/Lima" }) : "Sin registro";
async function read<T>(path: string, init?: RequestInit): Promise<T> {
  const response = await fetch(`/api/admin/${path}`, { ...init, cache: "no-store" });
  const body = await response.json();
  if (!response.ok) throw new Error(typeof body.detail === "string" ? body.detail : "No se pudo completar la solicitud");
  return body as T;
}
function Pagination({ page,total,setPage }: {page:number;total:number;setPage:(n:number)=>void}) {
  return <div className="admin-pagination"><span>{total} registros · Página {page}</span><button disabled={page===1} onClick={()=>setPage(page-1)}>Anterior</button><button disabled={page*25>=total} onClick={()=>setPage(page+1)}>Siguiente</button></div>;
}
function Timeline({ events }: {events:Event[]}) {
  return <ol className="admin-history">{events.map(e=><li key={e.event_id}><time>{date(e.created_at)}</time><div><b>{text(e.action)}</b><span>{text(e.outcome)} · {e.actor_type === "system" ? "Sistema" : e.actor_type === "admin" ? `Administrador #${e.actor_id ?? "operador"}` : `Usuario #${e.user_id}`}</span>{e.company_rpj && <Link href={`/empresas/${e.company_rpj}${e.resource_type === "report" ? `/notas/informe?year=${e.fiscal_year}&scope=${e.scope}` : ""}`}>{e.company_rpj} · {e.fiscal_year} · {e.scope}</Link>}{e.resource_type === "analysis" && e.resource_id && <a href={`/admin?jobId=${e.resource_id}`}>Inspeccionar trabajo #{e.resource_id}</a>}{e.resource_id && <small>{e.resource_type} #{e.resource_id}</small>}{e.source !== "recorded" && <small>{e.source === "historical" ? "Registro histórico disponible" : e.source === "baseline" ? "Captura previa; no reconstruye intentos" : e.source === "snapshot" ? "Último resultado disponible" : "Auditoría"}</small>}</div></li>)}{!events.length && <p>Sin registros para estos filtros. No implica ausencia de uso anterior.</p>}</ol>;
}
export function AdminDashboard() {
  const router = useRouter();
  const [tab,setTab] = useState("Resumen");
  useEffect(() => { if (/^\d+$/.test(new URLSearchParams(window.location.search).get("jobId") || "")) setTab("Análisis"); }, []);
  const [start,setStart] = useState(""); const [end,setEnd] = useState("");
  const [summary,setSummary] = useState<Summary|null>(null);
  const [listing,setListing] = useState<Listing|null>(null);
  const [audit,setAudit] = useState<{events:Audit[];total:number}|null>(null);
  const [selected,setSelected] = useState<User|null>(null); const [history,setHistory] = useState<History|null>(null);
  const [q,setQ] = useState(""); const [role,setRole] = useState(""); const [status,setStatus] = useState("");
  const [createdFrom,setCreatedFrom] = useState(""); const [createdTo,setCreatedTo] = useState(""); const [sort,setSort] = useState("created"); const [activeOnly,setActiveOnly] = useState(false);
  const [page,setPage] = useState(1); const [historyPage,setHistoryPage] = useState(1);
  const [actionFilter,setActionFilter] = useState(""); const [company,setCompany] = useState(""); const [outcome,setOutcome] = useState(""); const [actor,setActor] = useState("");
  const [change,setChange] = useState("revoke_sessions"); const [reason,setReason] = useState(""); const [confirmed,setConfirmed] = useState(false);
  const [busy,setBusy] = useState(false); const [error,setError] = useState(""); const [detailError,setDetailError] = useState(""); const [notice,setNotice] = useState(""); const [refresh,setRefresh] = useState(0);
  const period = new URLSearchParams(); if(start)period.set("start",start); if(end)period.set("end",end);
  const periodKey = period.toString();
  useEffect(()=>{let live=true;setError("");
    const query=new URLSearchParams(periodKey);query.set("page",String(page));
    if(tab==="Usuarios") { for(const [k,v] of Object.entries({q,role,status,sort,created_from:createdFrom,created_to:createdTo,active_only:String(activeOnly)}))if(v)query.set(k,v); setListing(null); }
    if(tab==="Resumen")setSummary(null);if(tab==="Auditoría")setAudit(null);
    const load=async()=>{try{if(tab==="Resumen"){const r=await read<Summary>(`summary?${query}`);if(live)setSummary(r);}else if(tab==="Usuarios"){const r=await read<Listing>(`users?${query}`);if(live)setListing(r);}else if(tab==="Auditoría"){const r=await read<{events:Audit[];total:number}>(`audit?${query}`);if(live)setAudit(r);}}catch(e){if(live)setError((e as Error).message);}};
    void load();return()=>{live=false;};
  },[tab,page,q,role,status,sort,createdFrom,createdTo,activeOnly,periodKey,refresh]);
  const selectedId=selected?.id;
  useEffect(()=>{if(!selectedId)return;let live=true;setHistory(null);setDetailError("");const query=new URLSearchParams(periodKey);query.set("page",String(historyPage));for(const [k,v] of Object.entries({action:actionFilter,company,outcome,actor_type:actor}))if(v)query.set(k,v);
    void read<History>(`users/${selectedId}/activity?${query}`).then(r=>{if(live)setHistory(r);}).catch(e=>{if(live)setDetailError(e.message);});return()=>{live=false;};
  },[selectedId,historyPage,actionFilter,company,outcome,actor,periodKey,refresh]);
  async function inspect(u:User){setDetailError("");setNotice("");setSelected(null);setConfirmed(false);setReason("");setHistoryPage(1);setActionFilter("");setCompany("");setOutcome("");setActor("");try{const r=await read<{user:User}>(`users/${u.id}`);setSelected(r.user);}catch(e){setError((e as Error).message);}}
  async function access(event:React.FormEvent){event.preventDefault();if(!selected||!confirmed)return;setBusy(true);setDetailError("");setNotice("");try{const r=await read<{user:User;revoked_sessions:number}>(`users/${selected.id}/access`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({action:change,reason})});setSelected(r.user);setNotice(`Cambio registrado. Sesiones revocadas: ${r.revoked_sessions}.`);setConfirmed(false);setReason("");setRefresh(v=>v+1);router.refresh();}catch(e){setDetailError((e as Error).message);}finally{setBusy(false);}}
  return <div className="admin-panel"><header className="app-header"><div><span className="overline">ADMINISTRACIÓN</span><h1>Usuarios y operación</h1><p>Fechas en Lima · Uso registrado y control de acceso.</p></div><button className="admin-button" onClick={()=>setRefresh(v=>v+1)}>Actualizar</button></header>
    <nav className="admin-tabs" aria-label="Secciones administrativas">{["Resumen","Análisis","Usuarios","Auditoría"].map(t=><button key={t} aria-pressed={tab===t} onClick={()=>{setTab(t);setPage(1);setSelected(null);}}>{t}</button>)}</nav>
    {tab!=="Análisis" && <div className="admin-filters"><label>Actividad desde<input type="date" value={start} onChange={e=>{setStart(e.target.value);setPage(1);setHistoryPage(1);}}/></label><label>Hasta<input type="date" value={end} onChange={e=>{setEnd(e.target.value);setPage(1);setHistoryPage(1);}}/></label><p className="admin-meta">Sin fechas: últimos 30 días. Las altas y solicitudes históricas tienen cobertura limitada.</p></div>}
    {error && <p className="form-error" role="alert">{error}</p>}
    {tab==="Análisis" && <AdminPanel/>}
    {tab==="Resumen" && !summary && !error && <p role="status">Cargando resumen…</p>}
    {tab==="Resumen" && summary && <><div className="admin-counts">{[["Cuentas totales",summary.total_users],["Habilitadas",summary.active_users],["Suspendidas",summary.suspended_users],["Altas del periodo",summary.registrations],["Usuarios con actividad",summary.users_with_activity],["Solicitudes de análisis",summary.analysis_requests],["Solicitudes de informes",summary.report_requests],["Estados fallidos del sistema",summary.failures]].map(([label,n])=><div className="admin-stat" key={label}><b>{n}</b><span>{label}</span></div>)}</div><p className="admin-meta">Usuarios con actividad: al menos un evento humano en el periodo. No indica conexión actual. Registro detallado desde {date(summary.tracking_started_at)}.</p><section className="admin-card"><h2>Actividad reciente</h2><Timeline events={summary.recent}/></section></>}
    {tab==="Usuarios" && <><div className="admin-filters"><label>Nombre o correo<input value={q} maxLength={100} onChange={e=>{setQ(e.target.value);setPage(1);}}/></label><label>Rol<select value={role} onChange={e=>{setRole(e.target.value);setPage(1);}}><option value="">Todos</option><option value="admin">Administrador</option><option value="user">Usuario</option></select></label><label>Estado<select value={status} onChange={e=>{setStatus(e.target.value);setPage(1);}}><option value="">Todos</option><option value="active">Habilitado</option><option value="suspended">Suspendido</option></select></label><label>Alta desde<input type="date" value={createdFrom} onChange={e=>{setCreatedFrom(e.target.value);setPage(1);}}/></label><label>Alta hasta<input type="date" value={createdTo} onChange={e=>{setCreatedTo(e.target.value);setPage(1);}}/></label><label>Orden<select value={sort} onChange={e=>{setSort(e.target.value);setPage(1);}}><option value="created">Alta reciente</option><option value="activity">Actividad reciente</option><option value="name">Nombre</option></select></label><label><span><input type="checkbox" checked={activeOnly} onChange={e=>{setActiveOnly(e.target.checked);setPage(1);}}/> Con actividad en el periodo</span></label></div>
      {!listing && !error && <p role="status">Cargando usuarios…</p>}{listing && <><p className="admin-meta">Actividad detallada desde {date(listing.tracking_started_at)}. Sin registro no significa que nunca haya usado la aplicación.</p><div className="admin-table-wrap"><table><thead><tr><th>Cuenta</th><th>Estado / rol</th><th>Alta</th><th>Último login</th><th>Última actividad</th><th>Solicitudes del periodo</th><th>Detalle</th></tr></thead><tbody>{listing.users.map(u=><tr key={u.id}><td>{u.full_name}<small>{u.email}</small></td><td>{u.is_active?"Habilitada":"Suspendida"}<small>{u.is_admin?"Administrador":"Usuario"}</small></td><td>{date(u.created_at)}</td><td>{date(u.last_login_at)}</td><td>{date(u.last_activity_at)}</td><td>{u.requests}</td><td><button className="admin-button" onClick={()=>void inspect(u)}>Ver cuenta</button></td></tr>)}</tbody></table></div><Pagination page={page} total={listing.total} setPage={setPage}/></>}
      {selected && <section className="admin-card"><header><h2>{selected.full_name}</h2><button className="admin-button" disabled={busy} onClick={()=>setSelected(null)}>Cerrar ficha</button></header><p>{selected.email} · #{selected.id} · {selected.is_active?"Habilitada":"Suspendida"} · {selected.is_admin?"Administrador":"Usuario"}</p>{selected.suspension_reason && <p>Motivo de suspensión: {selected.suspension_reason}</p>}{detailError && <p className="form-error" role="alert">{detailError}</p>}{notice && <p role="status">{notice}</p>}
        <form className="admin-retry" onSubmit={access}><h3>Control de acceso</h3><label>Acción<select value={change} onChange={e=>{setChange(e.target.value);setConfirmed(false);}}><option value="revoke_sessions">Cerrar todas las sesiones</option><option value="suspend">Suspender y cerrar sesiones</option><option value="reactivate">Reactivar cuenta</option><option value="grant_admin">Conceder permiso administrador</option><option value="revoke_admin">Retirar permiso administrador</option></select></label><label>Motivo<textarea required minLength={10} maxLength={500} value={reason} onChange={e=>setReason(e.target.value)}/></label><label><input type="checkbox" checked={confirmed} onChange={e=>setConfirmed(e.target.checked)}/> Confirmo la acción seleccionada sobre {selected.email}. La suspensión bloquea el acceso; el cambio de rol modifica sus permisos.</label><button className="admin-primary" disabled={busy||!confirmed||reason.trim().length<10}>{busy?"Registrando…":"Confirmar y registrar cambio"}</button></form>
        <h3>Historial</h3><div className="admin-filters"><label>Tipo<select value={actionFilter} onChange={e=>{setActionFilter(e.target.value);setHistoryPage(1);}}><option value="">Todos</option>{Object.keys(labels).filter(k=>k.includes(".")).map(k=><option key={k} value={k}>{labels[k]}</option>)}</select></label><label>Empresa (código)<input value={company} maxLength={20} onChange={e=>{setCompany(e.target.value);setHistoryPage(1);}}/></label><label>Resultado<select value={outcome} onChange={e=>{setOutcome(e.target.value);setHistoryPage(1);}}><option value="">Todos</option>{["success","observed","created","reused","retried","failed","completed","queued","running","retrying","review_required"].map(k=><option value={k} key={k}>{text(k)}</option>)}</select></label><label>Actor<select value={actor} onChange={e=>{setActor(e.target.value);setHistoryPage(1);}}><option value="">Todos</option><option value="human">Usuario</option><option value="system">Sistema</option><option value="admin">Administrador</option></select></label></div>
        {!history && !detailError && <p role="status">Cargando historial…</p>}{history && <><Timeline events={history.events}/><Pagination page={historyPage} total={history.total} setPage={setHistoryPage}/></>}
      </section>}</>}
    {tab==="Auditoría" && !audit && !error && <p role="status">Cargando auditoría…</p>}{tab==="Auditoría" && audit && <section className="admin-card"><h2>Auditoría administrativa</h2><p className="admin-meta">Incluye cambios de acceso y consultas de fichas e historiales. Ordenada por registro; filtrada por el periodo seleccionado.</p><ol className="admin-history">{audit.events.map(e=><li key={e.id}><time>{date(e.created_at)}</time><div><b>{text(e.action)}</b><span>{e.actor_label} · Usuario afectado #{e.target_user_id ?? "—"}</span><p>{e.reason}</p><details><summary>Valores y evidencia</summary><pre>{JSON.stringify(e.details,null,2)}</pre></details></div></li>)}</ol><Pagination page={page} total={audit.total} setPage={setPage}/></section>}
  </div>;
}
